version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: meu-vue-app
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - VITE_REVERB_APP_KEY=rpfnh21jtr3szlu5frah
      - VITE_REVERB_HOST=localhost
      - VITE_REVERB_PORT=6001
      - VITE_REVERB_SCHEME=ws
      - VITE_REVERB_CLUSTER=mt1
      - CHOKIDAR_USEPOLLING=true